### ISSUE TITLE
Update content editor role permissions

### ISSUE THREAD

**Issue by trubach** [ATLAS-Illinois/Illinois-Framework#23]
The content editor role should have these additional permissions:

- Bypass content access control (should be able to remove individual content type permissions as this should let them access them all)
- Administer media
- Administer menus and menu links
- Administer vocabularies and terms
- Access the taxonomy vocabulary overview page
- View the administration theme

REMOVE:
- View site reports

**Comment by trubach** [comment]
@nbaxley-uiuc - do you think we should discuss these changes in the larger Drupal group?

**Comment by nbaxley-uiuc** [comment]
@mwllr From our tests, these permissions were needed for people to be able to fully manage the content on a site.  What do you think?
