### ISSUE TITLE
Media Library permissions

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework#36]
- [ ] Set media permissions for Content Manager role

**Comment by magjarvis** [comment]
![Screenshot 2023-06-09 135211](https://github.com/web-illinois/illinois_framework_core/assets/8452264/d51cee9d-291d-4214-9f7b-602d1fbf8645)
![Screenshot 2023-06-09 135240](https://github.com/web-illinois/illinois_framework_core/assets/8452264/a4197a0d-fabe-4f9a-b90f-76ec363129c0)

**Comment by trubach** [comment]
Fixed in commit fffd409 - linked above
